Source = \
	Azure.java \
	AzureAttachment.java \
	AzureComment.java \
	AzureUser.java \
	AzureWorkItem.java \
	ISO8601DateParser.java \
	Jira.java \
	JiraAttachment.java \
	JiraComment.java \
	JiraIssue.java \
	JiraLink.java \
	JiraPullRequest.java \
	JiraReaction.java \
	JiraUser.java \
	MigrationTool.java \
	Util.java \
	YouTrack.java \
	YouTrackAttachment.java \
	YouTrackComment.java \
	YouTrackIssue.java \
	YouTrackLink.java \
	YouTrackUser.java \

#Main = MigrationTool
Main = Azure

include $(DEV_HOME)/Test/Makefile
